apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    service: auth
    chart: {{ template "smartcheck.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: external
  selector:
    service: auth
    release: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: auth-internal
  labels:
    service: auth-internal
    chart: {{ template "smartcheck.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 8081
      protocol: TCP
      name: internal
  selector:
    service: auth
    release: {{ .Release.Name }}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth
  labels:
    service: auth
    chart: {{ template "smartcheck.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ default 1 .Values.replicas.auth }}
  template:
    metadata:
      labels:
        service: auth
        chart: {{ template "smartcheck.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      {{- $imageDefaults := .Values.images.defaults }}
      {{- with .Values.images.auth }}
      {{- $secret := (default $imageDefaults.imagePullSecret .imagePullSecret) | quote }}
      {{- if not (eq "" $secret) }}
      imagePullSecrets:
        - name: {{ $secret }}
      {{- end }}
      containers:
        - name: auth
          {{- $project := (default (default "deepsecurity" $imageDefaults.project) .project) }}
          {{- $repository := printf "%s/%s" $project (required ".repository is required!" .repository) }}
          {{- $tag := (default $imageDefaults.tag .tag) }}

          {{- if eq (default "" .registry) "-" }}
          image: {{ printf "%s:%s" $repository $tag | quote }}
          {{- else if eq (default "-" $imageDefaults.registry) "-" }}
          image: {{ printf "%s:%s" $repository $tag | quote }}
          {{- else }}
          image: {{ printf "%s/%s:%s" (default $imageDefaults.registry .registry) $repository $tag | quote }}
          {{- end }}
          imagePullPolicy: {{ default (default "Always" $imageDefaults.pullPolicy) .pullPolicy }}
          {{- end }}
          ports:
            - containerPort: 8080
              name: external
            - containerPort: 8081
              name: internal
            - containerPort: 8082
              name: metrics
            - containerPort: 8083
              name: health
          livenessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          args:
            - --internal-base=http://auth-internal:8081
            - --authorization-url=http://auth-internal:8081
            - --database-connection-string=postgres:host=db user=$(DB_USER) password=$(DB_PASSWORD) dbname=authdb sslmode=disable connect_timeout=5 # seconds
            - --database-secret=$(DB_SECRET)
            - --initial-role={{ default "admin" .Values.auth.roleName }}
            - --initial-user=$(INITIAL_USER)
            - --initial-password=$(INITIAL_PASSWORD)
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: {{ template "smartcheck.fullname" . }}-db
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: {{ template "smartcheck.fullname" . }}-db
            - name: DB_SECRET
              valueFrom:
                secretKeyRef:
                  key: database-secret
                  name: {{ template "smartcheck.fullname" . }}-db
            - name: INITIAL_USER
              valueFrom:
                secretKeyRef:
                  key: userName
                  name: {{ template "smartcheck.fullname" . }}-auth
            - name: INITIAL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ template "smartcheck.fullname" . }}-auth
          resources:
{{ toYaml (default .Values.resources.defaults .Values.resources.auth) | indent 12 }}
      nodeSelector:
{{ toYaml (default .Values.nodeSelector.defaults .Values.nodeSelector.auth) | indent 8 }}
      tolerations:
{{ toYaml (default .Values.tolerations.defaults .Values.tolerations.auth) | indent 8 }}
      restartPolicy: Always

{{ if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: auth
  labels:
    service: auth
    chart: {{ template "smartcheck.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      service: auth
      chart: {{ template "smartcheck.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              service: proxy
              chart: {{ template "smartcheck.chart" . }}
              release: {{ .Release.Name }}
              heritage: {{ .Release.Service }}
      ports:
        - protocol: TCP
          port: 8080
    - from:
        - podSelector:
            matchLabels:
              service: registryviews
              chart: {{ template "smartcheck.chart" . }}
              release: {{ .Release.Name }}
              heritage: {{ .Release.Service }}
        - podSelector:
            matchLabels:
              service: scan
              chart: {{ template "smartcheck.chart" . }}
              release: {{ .Release.Name }}
              heritage: {{ .Release.Service }}
        - podSelector:
            matchLabels:
              service: auth
              chart: {{ template "smartcheck.chart" . }}
              release: {{ .Release.Name }}
              heritage: {{ .Release.Service }}
      ports:
        - protocol: TCP
          port: 8081
    - from: # any -- this is for metrics
      ports:
        - protocol: TCP
          port: 8082
    - from: # any -- this should just be kubelet for health probes
      ports:
        - protocol: TCP
          port: 8083
  egress:
    - to:
        - podSelector:
            matchLabels:
              service: db
              chart: {{ template "smartcheck.chart" . }}
              release: {{ .Release.Name }}
              heritage: {{ .Release.Service }}
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - podSelector:
            matchLabels:
              service: auth
              chart: {{ template "smartcheck.chart" . }}
              release: {{ .Release.Name }}
              heritage: {{ .Release.Service }}
      ports:
        - protocol: TCP
          port: 8081
    - to: # any
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
{{- end }}
