apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    service: auth
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $k, $v := (default (dict) .Values.extraLabels) }}
    {{ $k }}: {{ quote $v }}
    {{- end }}{{/* range .Values.extraLabels */}}
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: external
  selector:
    service: auth
    release: {{ .Release.Name }}

---
{{ include "smartcheck.service.database.secret" (dict "Chart" .Chart "Values" .Values "Release" .Release "service" "auth") }}
---
{{ include "smartcheck.auth.initial-user.secret" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: auth-internal
  labels:
    service: auth-internal
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $k, $v := (default (dict) .Values.extraLabels) }}
    {{ $k }}: {{ quote $v }}
    {{- end }}{{/* range .Values.extraLabels */}}
spec:
  ports:
    - port: 8081
      protocol: TCP
      name: internal
  selector:
    service: auth
    release: {{ .Release.Name }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    service: auth
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    appVersion: {{ .Chart.AppVersion }}
    metrics: include
    {{- range $k, $v := (default (dict) .Values.extraLabels) }}
    {{ $k }}: {{ quote $v }}
    {{- end }}{{/* range .Values.extraLabels */}}
spec:
  # We set revisionHistoryLimit to 0 because rollback should be done
  # using `helm rollback` rather than with `kubectl rollout undo`, so
  # we don't need to keep the old `ReplicaSet`s around.
  # https://kubernetes.io/docs/concepts/workloads/controllers/deployment
  revisionHistoryLimit: 0
  replicas: {{ default 1 .Values.replicas.auth }}
  selector:
    matchLabels:
      service: auth
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        service: auth
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        appVersion: {{ .Chart.AppVersion }}
        metrics: include
        {{- range $k, $v := (default (dict) .Values.extraLabels) }}
        {{ $k }}: {{ quote $v }}
        {{- end }}{{/* range .Values.extraLabels */}}
    spec:
      automountServiceAccountToken: false
      {{- $securityContextEnabled := .Values.securityContext.enabled }}
      {{- $securityContext := default .Values.securityContext.default .Values.securityContext.auth }}
      {{- $podSecurityContext := default .Values.securityContext.default.pod $securityContext.pod }}
      {{- $containerSecurityContext := default .Values.securityContext.default.container $securityContext.container }}
      {{- if $securityContextEnabled }}
      securityContext: {{ toYaml $podSecurityContext | nindent 8 }}
      {{- end }}{{/* if $securityContextEnabled */}}
      initContainers:
        - {{ include "smartcheck.db-initcontainer" (dict "Values" .Values "Chart" .Chart "Release" .Release "service" "auth") | nindent 10 | trim }}

      {{- $imageDefaults := .Values.images.defaults }}
      {{- with .Values.images.auth }}
      {{- $secret := (default (default "" $imageDefaults.imagePullSecret) .imagePullSecret) }}
      {{- if $secret }}
      imagePullSecrets:
        - name: {{ $secret | quote }}
      {{- end }}{{/* if $secret */}}
      containers:
        - name: auth
          {{- if $securityContextEnabled }}
          securityContext: {{ toYaml $containerSecurityContext | nindent 12 }}
          {{- end }}
          {{- $project := (default (default "deepsecurity" $imageDefaults.project) .project) }}
          {{- $repository := printf "%s/%s" $project (required ".repository is required!" .repository) }}
          {{- $tag := (default $imageDefaults.tag .tag) }}
          image: {{ include "image.source" (dict "repository" $repository "registry" .registry "tag" $tag "imageDefaults" $imageDefaults "digest" .digest) }}
          imagePullPolicy: {{ default (default "Always" $imageDefaults.pullPolicy) .pullPolicy }}
          {{- end }}{{/* with .Values.images.auth */}}
          ports:
            - containerPort: 8080
              name: external
            - containerPort: 8081
              name: internal
            - containerPort: 8082
              name: metrics
            - containerPort: 8083
              name: health
          livenessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          args:
            - --internal-base=http://auth-internal:8081
            - --authorization-url=http://localhost:8081 # see https://github.com/kubernetes/kubernetes/issues/61593
            - --database-connection-string=postgres:postgres://
            - --database-secret=$(DB_SECRET)
            - --initial-role={{ default "admin" .Values.auth.roleName }}
            - --auditor-role={{ default "auditor" .Values.auth.auditorRoleName }}
            - --user-role={{ default "user" .Values.auth.userRoleName }}
            - --initial-user=$(INITIAL_USER)
            - --initial-password=$(INITIAL_PASSWORD)
            - --token-audience={{ default "deepsecurity-smartcheck" .Values.auth.tokenAudience }}
            - --use-strict-transport-security=true
            - --use-strict-transport-security-includes-subdomains=false
            - --use-strict-transport-security-includes-preload=false
            {{- if .Values.auth.saml.enabled }}
            - --saml-entity-id={{ .Values.auth.saml.entityID }}
            - --saml-assertion-consumer-url={{ .Values.auth.saml.location }}
            - --saml-max-roles={{ default 10 .Values.auth.saml.maxRoles }}
            {{- end }}{{/* if .Values.auth.saml.enabled */}}
            {{- if .Values.telemetry.enabled }}
            - --telemetry-endpoint=http://metrics-internal:8081
            {{- end }}
            {{- if .Values.auth.sessionDuration }}
            - --token-lifetime={{ .Values.auth.sessionDuration }}
            {{- end }}{{/* if .Values.auth.sessionDuration */}}
            {{- if .Values.auth.sessionKeyLifetime }}
            - --token-key-lifetime={{ .Values.auth.sessionKeyLifetime }}
            {{- end }}{{/* if .Values.auth.sessionKeyLifetime */}}
          env:
            {{- include "smartcheck.service.database.env" (dict "Chart" .Chart "Release" .Release "Values" .Values "service" "auth") | nindent 12 }}
            {{- include "smartcheck.proxy.env" . | nindent 12 }}
            - name: _INITIAL_USER_SECRET_CHECKSUM
              value: {{ include "smartcheck.auth.initial-user.secret" . | sha256sum }}
            - name: INITIAL_USER
              valueFrom:
                secretKeyRef:
                  key: userName
                  name: {{ template "smartcheck.fullname" . }}-auth
            - name: INITIAL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ template "smartcheck.fullname" . }}-auth
          volumeMounts:
            {{- $volumeMounts := include "smartcheck.db-trust-volume-mount" . | nindent 12 }}
            {{- if (trim $volumeMounts) }}
            {{- $volumeMounts }}
            {{- else }}
            []
            {{- end }}{{/* if $volumeMounts */}}
          resources: {{ toYaml (default .Values.resources.defaults .Values.resources.auth) | nindent 12 }}
      volumes:
        {{- $volumes := include "smartcheck.db-trust-volume" . | nindent 8 }}
        {{- if (trim $volumes) }}
        {{- $volumes }}
        {{- else }}
        []
        {{- end }}{{/* if $volumes */}}
      nodeSelector: {{ toYaml (default .Values.nodeSelector.defaults .Values.nodeSelector.auth) | nindent 8 }}
      tolerations: {{ toYaml (default .Values.tolerations.defaults .Values.tolerations.auth) | nindent 8 }}
      restartPolicy: Always

{{ if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: auth
  labels:
    service: auth
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $k, $v := (default (dict) .Values.extraLabels) }}
    {{ $k }}: {{ quote $v }}
    {{- end }}{{/* range .Values.extraLabels */}}
spec:
  podSelector:
    matchLabels:
      service: auth
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      {{- range $k, $v := (default (dict) .Values.extraLabels) }}
      {{ $k }}: {{ quote $v }}
      {{- end }}{{/* range .Values.extraLabels */}}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              service: proxy
              release: {{ .Release.Name }}
              heritage: {{ .Release.Service }}
              {{- range $k, $v := (default (dict) .Values.extraLabels) }}
              {{ $k }}: {{ quote $v }}
              {{- end }}{{/* range .Values.extraLabels */}}
      ports:
        - protocol: TCP
          port: 8080
    - from:
        - podSelector:
            matchLabels:
              service: registryviews
              release: {{ .Release.Name }}
              heritage: {{ .Release.Service }}
              {{- range $k, $v := (default (dict) .Values.extraLabels) }}
              {{ $k }}: {{ quote $v }}
              {{- end }}{{/* range .Values.extraLabels */}}
        - podSelector:
            matchLabels:
              service: scan
              release: {{ .Release.Name }}
              heritage: {{ .Release.Service }}
              {{- range $k, $v := (default (dict) .Values.extraLabels) }}
              {{ $k }}: {{ quote $v }}
              {{- end }}{{/* range .Values.extraLabels */}}
        - podSelector:
            matchLabels:
              service: auth
              release: {{ .Release.Name }}
              heritage: {{ .Release.Service }}
              {{- range $k, $v := (default (dict) .Values.extraLabels) }}
              {{ $k }}: {{ quote $v }}
              {{- end }}{{/* range .Values.extraLabels */}}
        - podSelector:
            matchLabels:
              service: license
              release: {{ .Release.Name }}
              heritage: {{ .Release.Service }}
              {{- range $k, $v := (default (dict) .Values.extraLabels) }}
              {{ $k }}: {{ quote $v }}
              {{- end }}{{/* range .Values.extraLabels */}}
      ports:
        - protocol: TCP
          port: 8081
    - from: # any -- this is for metrics
      ports:
        - protocol: TCP
          port: 8082
    - from: # any -- this should just be kubelet for health probes
      ports:
        - protocol: TCP
          port: 8083
  egress:
    {{- include "smartcheck.to-dns-networkpolicy" . | nindent 4 }}
    {{- include "smartcheck.to-db-networkpolicy" . | nindent 4 }}
    {{- include "smartcheck.to-internal-service-networkpolicy" (dict "Release" .Release "Values" .Values "services" (list "auth" "metrics")) | nindent 4 }}
    # allow egress on ports 443 / 80 for access to SAML metadata
    - to: # any
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
{{- end }}{{/* if networkPolicy.enabled */}}
