apiVersion: v1
kind: Secret
metadata:
  name: {{ template "smartcheck.fullname" . }}-db
  labels:
    app: {{ template "smartcheck.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- range $k, $v := (default (dict) .Values.extraLabels) }}
    {{ $k }}: {{ quote $v }}
{{- end }}
type: Opaque
data:
  {{ if .Values.db.user -}}
  database-user: {{ .Values.db.user | toString | b64enc | quote }}
  {{ else -}}
  database-user: {{ derivePassword 1 "maximum" (toString (required "You must provide a value for auth.secretSeed. Use --set auth.secretSeed={password} or include a value in your overrides.yaml file." (default .Values.auth.masterPassword .Values.auth.secretSeed))) "db-user" .Release.Name | toString | b64enc | quote }}
  {{ end -}}
  {{ if .Values.db.password -}}
  database-password: {{ .Values.db.password | toString | b64enc | quote }}
  {{ else -}}
  database-password: {{ derivePassword 1 "maximum" (toString (default .Values.auth.masterPassword .Values.auth.secretSeed)) "db-password" .Release.Name | toString | b64enc | quote }}
  {{ end -}}
  {{ if .Values.db.secret -}}
  database-secret: {{ .Values.db.secret | toString | b64enc | quote }}
  {{ else -}}
  database-secret: {{ derivePassword 1 "maximum" (toString (default .Values.auth.masterPassword .Values.auth.secretSeed)) "db-secret" .Release.Name | toString | b64enc | quote }}
  {{- end }}

{{ if not .Values.certificate.secret.name }}
---
apiVersion: v1
kind: Secret
metadata:
  name:  {{ template "smartcheck.fullname" . }}-tls-certificate
  labels:
    app: {{ template "smartcheck.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- range $k, $v := (default (dict) .Values.extraLabels) }}
    {{ $k }}: {{ quote $v }}
{{- end }}
type: Opaque
data:
  {{- with .Values.certificate }}
  {{- $cert := genSelfSignedCert (default "example.com" .commonName) (default nil .ipAlternativeNames) (default nil .dnsAlternativeNames) (default 3650 (int .lifetime)) }}
  privateKey: {{ $cert.Key | b64enc | quote }}
  certificate: {{ $cert.Cert | b64enc | quote }}
  {{- end }}
{{ end }}

